create table users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    enabled boolean not null default true,
    account_non_locked boolean not null default true,
    status varchar(30) not null default 'ACTIVE',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email),
    constraint ck_users_status check (status in ('ACTIVE', 'DELETED'))
);
