create table orders (
    id bigint generated by default as identity primary key,
    order_number varchar(40) not null,
    customer_id bigint not null,
    order_status varchar(30) not null default 'PENDING_PAYMENT',
    total_amount numeric(19, 2) not null default 0,
    currency varchar(3) not null,
    shipping_address varchar(500) not null,
    payment_reference varchar(100),
    tracking_number varchar(100),
    status varchar(30) not null default 'ACTIVE',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_by bigint,
    deleted_at timestamp,
    constraint uk_orders_order_number unique (order_number),
    constraint fk_orders_customer foreign key (customer_id) references users (id),
    constraint ck_orders_status check (status in ('ACTIVE', 'DELETED')),
    constraint ck_orders_order_status check (order_status in (
        'PENDING_PAYMENT', 'PAID', 'PAYMENT_FAILED', 'SHIPPED', 'DELIVERED', 'CANCELLED'
    ))
);

create index ix_orders_customer_id on orders (customer_id);
create index ix_orders_order_status on orders (order_status);
create index ix_orders_created_at on orders (created_at);
create index ix_orders_payment_reference on orders (payment_reference);

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_name varchar(255) not null,
    product_sku varchar(100) not null,
    quantity integer not null,
    unit_price numeric(19, 2) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_by bigint,
    constraint fk_order_items_order foreign key (order_id) references orders (id) on delete cascade,
    constraint ck_order_items_quantity check (quantity > 0),
    constraint ck_order_items_unit_price check (unit_price > 0)
);

create index ix_order_items_order_id on order_items (order_id);

create table order_status_history (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    previous_status varchar(30),
    new_status varchar(30) not null,
    reason varchar(500),
    source varchar(50) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    created_by bigint,
    updated_by bigint,
    constraint fk_order_status_history_order foreign key (order_id) references orders (id) on delete cascade
);

create index ix_order_status_history_order_id on order_status_history (order_id);
create index ix_order_status_history_created_at on order_status_history (created_at);
