create table webhook_events (
                                id bigint generated by default as identity primary key,
                                channel varchar(30) not null,
                                event_type varchar(100) not null,
                                provider_event_id varchar(150) not null,
                                order_number varchar(40),
                                payload text not null,
                                signature_valid boolean not null default false,
                                status varchar(30) not null default 'RECEIVED',
                                error_message varchar(1000),
                                processed_at timestamp,
                                created_at timestamp not null default current_timestamp,
                                updated_at timestamp not null default current_timestamp,
                                created_by bigint,
                                updated_by bigint,
                                constraint uk_webhook_events_channel_provider_event_id unique (channel, provider_event_id),
                                constraint ck_webhook_events_channel check (channel in ('PAYMENT', 'SHIPMENT')),
                                constraint ck_webhook_events_status check (status in ('RECEIVED', 'PROCESSED', 'FAILED', 'IGNORED'))
);

create index ix_webhook_events_order_number on webhook_events (order_number);
create index ix_webhook_events_status on webhook_events (status);
create index ix_webhook_events_created_at on webhook_events (created_at);